-- MySQL Script generated by MySQL Workbench
-- Mon Sep  6 08:41:15 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema 1812843_mysql
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 1812843_mysql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `1812843_mysql` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `1812843_mysql` ;

-- -----------------------------------------------------
-- Table `1812843_mysql`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `1812843_mysql`.`orders` (
  `orderNumber` INT NOT NULL AUTO_INCREMENT,
  `orderDate` DATETIME NULL DEFAULT NULL,
  `requiredDate` DATETIME NULL DEFAULT NULL,
  `shippedDate` DATETIME NULL DEFAULT NULL,
  `status` VARCHAR(15) NULL DEFAULT NULL,
  `comments` TEXT NULL DEFAULT NULL,
  `customerNumber` INT NULL DEFAULT NULL,
  PRIMARY KEY (`orderNumber`))
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `1812843_mysql`.`productlines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `1812843_mysql`.`productlines` (
  `productLine` VARCHAR(50) NOT NULL,
  `textDescription` VARCHAR(4000) NULL DEFAULT NULL,
  `htmlDescription` MEDIUMTEXT NULL DEFAULT NULL,
  `image` MEDIUMBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`productLine`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `1812843_mysql`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `1812843_mysql`.`products` (
  `productCode` VARCHAR(15) NOT NULL,
  `productName` VARCHAR(70) NULL DEFAULT NULL,
  `Branch` VARCHAR(50) NULL DEFAULT NULL,
  `productScale` VARCHAR(10) NULL DEFAULT NULL,
  `productVendor` VARCHAR(50) NULL DEFAULT NULL,
  `productDescription` TEXT NULL DEFAULT NULL,
  `quantityInStock` SMALLINT NULL DEFAULT NULL,
  `buyPrice` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`productCode`),
  INDEX `productLine` (`Branch` ASC) VISIBLE,
  CONSTRAINT `products_ibfk_1`
    FOREIGN KEY (`Branch`)
    REFERENCES `1812843_mysql`.`productlines` (`productLine`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `1812843_mysql`.`orderdetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `1812843_mysql`.`orderdetails` (
  `orderNumber` INT NOT NULL AUTO_INCREMENT,
  `productCode` VARCHAR(15) NOT NULL,
  `quantityOrdered` INT NULL DEFAULT NULL,
  `priceEach` DOUBLE NULL DEFAULT NULL,
  `orderLineNumber` INT NULL DEFAULT NULL,
  PRIMARY KEY (`orderNumber`, `productCode`),
  INDEX `productCode` (`productCode` ASC) VISIBLE,
  CONSTRAINT `orderdetails_ibfk_1`
    FOREIGN KEY (`orderNumber`)
    REFERENCES `1812843_mysql`.`orders` (`orderNumber`)
    ON UPDATE CASCADE,
  CONSTRAINT `orderdetails_ibfk_2`
    FOREIGN KEY (`productCode`)
    REFERENCES `1812843_mysql`.`products` (`productCode`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
